export const imagen1 = "/assets/asd.png";
export const KMWhite = "/assets/KM-white.jpeg";
export const KMBlack = "/assets/KM-black.jpeg";
export const lucas = "/assets/lucas.jpeg";
export const lucas1 = "/assets/lucas1.jpeg";
export const lucas2 = "/assets/lucas2.jpeg";
export const lucas3 = "/assets/lucas3.jpeg";
export const lucas4 = "/assets/lucas4.jpeg";
export const lucas5 = "/assets/lucas5.jpeg";
export const lucas6 = "/assets/lucas6.jpeg";
export const lucas7 = "/assets/lucas7.jpeg";
export const lucas8 = "/assets/lucas8.jpeg";
export const lucas9 = "/assets/lucas9.jpeg";
export const lucas10 = "/assets/lucas10.jpeg";
export const lucasBottomless1 = "/assets/lucas1-sin-fondo.jpeg";
export const lucasBottomless2 = "/assets/lucas2-sin-fondo.jpeg";
export const lucasBottomless3 = "/assets/lucas3-sin-fondo.jpeg";
export const lucasBottomless4 = "/assets/lucas4-sin-fondo.jpeg";

export const TestimonialImages = [
  "/assets/Testimony1.jpeg",
  "/assets/Testimony2.jpeg",
  "/assets/Testimony3.jpeg",
  "/assets/Testimony4.jpeg",
  "/assets/Testimony6.jpeg",
  "/assets/Testimony7.jpeg",
  "/assets/Testimony8.jpeg",
  "/assets/Testimony9.jpeg",
  "/assets/Testimony10.jpeg",
  "/assets/Testimony11.jpeg",
  "/assets/Testimony12.jpeg",
  "/assets/Testimony13.jpeg",
  "/assets/Testimony15.jpeg",
];

export const TransformationsImages = [
  "/assets/trasnformation1.jpeg",
  "/assets/trasnformation2.jpeg",
  "/assets/trasnformation3.jpeg",
  "/assets/trasnformation4.jpeg",
  "/assets/trasnformation5.jpeg",
  "/assets/trasnformation6.jpeg",
  "/assets/trasnformation7.jpeg",
];

export const Questions = [
  {
    question: "¿En qué nos diferenciamos de otros programas?",
    response:
      "Resultados, profesionalismo, eficiencia, eficacia, experiencia en carne propia, atención personalizada y acompañamiento son puntos clave en los que nos sentimos muy identificados. Como integrante del team de kmprofitness aprenderás a comer y entrenar de manera óptima para promover los cambios que tu salud necesita, para ello tendrás un equipo de profesionales a tu disposición diariamente para brindarte la ayuda necesaria; evaluaremos la ejecución de los ejercicios y lo que comes día a día si crees necesario.",
  },
  {
    question: "¿Cómo funciona?",
    response:
      "Después de realizar el pago y proporcionar tus datos, te llegara un email con acceso exclusivo a nuestra aplicación, donde encontrarás una sección llamada Primer Paso. Aquí, tendrás a tu disposición una ficha técnica para completar con tus datos personales. Este paso es crucial, ya que nos permitirá conocer todo lo necesario sobre ti para personalizar tu programa fitness de manera única. Este proceso de recopilación de información tiene una estimación de 4 días hábiles. Una vez que hayamos elaborado cuidadosamente tus planificaciones, podrás visualizarlas directamente en la pantalla principal (Home) de la aplicación desde tu dispositivo móvil. Aquí, encontrarás un enlace directo que te conectará con tu entrenador o nutricionista asignado para resolver cualquier duda que pueda surgir durante tu viaje hacia la salud y la forma física. Nuestra meta es brindarte una experiencia personalizada, eficiente y respaldada por profesionales, asegurándonos de que cada paso que tomes te acerque a tus objetivos de bienestar. ¡Estamos aquí para guiarte en cada paso del camino!",
  },
  {
    question: "¿Cómo recibo mi programa?",
    response:
      "Tardamos 4 días hábiles una vez que llenas el cuestionario con todos tus datos, para acceder al programa tenes que entrar en la app la cual te llega por email al inscribirte.",
  },
  {
    question: "¿Es este un programa de suscripción?",
    response:
      "Sí, elegí estructurarlo de esta manera para asegurar que puedas mantener y avanzar en tu progreso, ya que el mantenimiento es esencial. Ofrecemos la flexibilidad de una suscripción mensual, lo que implica actualizaciones regulares en tus programas de entrenamiento y nutrición, diseñados específicamente para ti según el plan seleccionado. Además, contarás con mi apoyo constante y el respaldo de mi equipo a lo largo de tu trayecto.",
  },
  {
    question: "¿Cómo puedo cancelar mi suscripción?",
    response:
      "Para cancelar tu suscripción, simplemente envía un correo electrónico con al menos 7 días de antelación a la fecha de cobro. Es importante tener en cuenta que el periodo mínimo de permanencia es de 3 meses, ya que este tiempo es esencial para lograr un progreso significativo. Ten en cuenta que al cancelar, perderás el acceso tanto a la aplicación como a toda la ayuda con nuestros profesionales. Nuestro objetivo es asegurar un compromiso significativo para optimizar tus resultados.",
  },
  {
    question: "¿Para quién esta creado?",
    response:
      "Nuestro enfoque único se adapta a una variedad de audiencias: desde aquellos que dan sus primeros pasos en el mundo del fitness hasta deportistas ávidos que buscan llevar su rendimiento al siguiente nivel. Este programa no tiene límites de género ni restricciones de edad; es para hombres y mujeres de todas las edadesPara aquellos que dan sus primeros pasos, te brindamos una introducción amigable y personalizada al mundo del fitness. Si eres un deportista en busca de mejorar tu rendimiento, nuestras estrategias personalizadas te llevarán a nuevas alturas. Imagina un programa diseñado no solo para obtener resultados, sino para hacerlo de manera sostenible y adaptada a tu estilo de vida. No importa si eres principiante o experimentado, si buscas mejorar tu forma física o alcanzar metas deportivas específicas, nuestro enfoque integral se ajusta a tus necesidades. No esperes más para unirte a nuestra comunidad de transformación. ¡Eleva tu bienestar, desata tu potencial y descubre lo que realmente significa vivir en tu mejor versión! Este programa es para todos, ¡y eso incluye a TI!",
  },
  {
    question: "¿Necesito experiencia previa en fitness?",
    response:
      "No, el asesoramiento esta diseñado para todos los niveles, desde principantes hasta atletas avanzados. Adaptamos los ejercicios y la nutricion a tu nivel actual y vamos prograsando a tu ritmo",
  },
  {
    question: "¿Funciona el asesoramiento?",
    response:
      "Si, Descubre la eficacia de nuestro asesoramiento fitness consultando nuestros perfiles, donde hemos cosechado más de 3000 resultados en estos 7 años de dedicación. Te garantizamos que, al seguir tus planificaciones y aprovechar la experiencia de nuestros profesionales, experimentarás resultados constantes. Confía en nuestro historial de éxito y haz de tu viaje fitness una experiencia transformadora. ¡Los resultados hablan por sí mismos!",
  },
  {
    question: "¿Cómo se mide mi progreso?",
    response:
      "Dentro de la app kmpro vas a encontrar un apartado en donde podrás dejarnos tus medidas, peso e imágenes corporales. Estos datos van a conservarse y veremos a largo plazo tus progresos. También te dejaremos una devolución y aconsejaremos.",
  },
  {
    question: "¿Trabajan con un nutricionista?",
    response: "Si, en nuestro equipo contamos con nutricionista, los planes son personalizados",
  },
  {
    question: "¿Qué tipo de equipamiento necesito?",
    response:
      "Dependiendo de tus objetivos podemos trabajar con el equipamiento que tengas diponible, sino puedes asistir a un gimnacio, podemos crear un plan para que puedas seguir desde la comodidad de tu casa o al aire libre.",
  },
  {
    question: "¿Son planificaciones personalizadas?",
    response:
      "Si, tanto las planificaciones de entrenamiento como las de alimentacion son personalizadas. Se adaptan a tus necesides, objetivos y preferencias, garantizando que se ajusten a tu estilo de vida y te ayuden a alcanzar tus metas de manera efectiva.",
  },
  {
    question: "¿Que sucede si no puedo seguir el programa?",
    response:
      "Si tienes dificultades, lo mas importante es comunicarnos. Podemos ajustar tu programa segun tus necesidades, sean por cambios en tu rutina, lesiones o cualquier otra razon.",
  },
];

export const Countries = [
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Barbados",
  "Baréin",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Ciudad del Vaticano",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guyana",
  "Guinea",
  "Guinea ecuatorial",
  "Guinea-Bisáu",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Palestina",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República de Macedonia",
  "República del Congo",
  "República Democrática del Congo",
  "República Dominicana",
  "República Sudafricana",
  "Ruanda",
  "Rumanía",
  "Rusia",
  "Samoa",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Suazilandia",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
];

export const Plans = {
  "deportista-de-alto-nivel": { title: "Deportista de alto nivel", unit_price: 500, quantity: 1 },
  "aumento-muscular": { title: "Aumento muscular", unit_price: 100, quantity: 1 },
  "perdida-de-grasa": { title: "Perdida de grasa y recomposición corporal", unit_price: 30, quantity: 1 },
};

export const planUrls = {
  aumentoMasa: {
    1: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5ebe0192261073f41299",
    3: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f5701922613477b12d1",
    6: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5ebe01922617f90b129b",
  },
  perdidaGrasa: {
    1: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f570192261a28da12d6",
    3: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f1c0192261b3430126a",
    6: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f570192261c274312d7",
  },
  altoRendimiento: {
    1: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f570192261ee20612d8",
    3: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f570192261fe94712d9",
    6: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c93808491eb5f1c019226208fab126c",
  },
};
